import './slider/sliderNews';
import './slider/sliderHero';
import './menu/openMenu';
import './scroll/scrollTo';
import './scroll/stickyHeader';
import './btn/moreDetails';
import './btn/seeMoreBtn';
import './form/validateForm';
import './popup/popup'
